[package]
name = "project-euler"
version = "0.1.0"
authors = ["Vancha <tjipke@tutanota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigint-base10 = "0.1.1"
num-bigint = "0.3.0"
